pipeline:
  build_publish_npm:
    commands:
      - npm i
      - npm test
      - npm lint
      - npm publish
    image: node:8
    secrets:
      - npm_config__auth
      - npm_config_registry
      - npm_config_email
    environment:
      - NPM_CONFIG_ALWAYS_AUTH=true
    when:
      event: push
      branch: master
