pipeline:

  test:
    image: node:8
    secrets:
      - npm_config__auth
      - npm_config_registry
      - npm_config_email
    environment:
      - NPM_CONFIG_ALWAYS_AUTH=true
    commands:
      - npm i
      - npm test
    when:
      event: [push, tag]

  publish_to_artifactory:

    image: node:8
    secrets:
      - npm_config__auth
      - npm_config_registry
      - npm_config_email
    environment:
      - NPM_CONFIG_ALWAYS_AUTH=true
    commands:
      - npm publish
    when:
      event:
        - push
        - tag

matrix:
  NPM_CONFIG_USERNAME:
    - regt-build-bot

